- name: Test SSH connection
  uses: appleboy/ssh-action@v0.1.5
  with:
    host: ${{ secrets.AWS_SSH_HOST }}
    username: ${{ secrets.AWS_SSH_USER }}
    key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
    port: 22
    script: |
      echo "SSH connection successful"